//module.exports.TEST_CEDULA = "19304877";
module.exports.TEST_CEDULA = "1026568457";
module.exports.DBC_EMAIL = "ortegon.carlos@gmail.com";
module.exports.DBC_KEY = "nm80vdBUE4OX26gB2UyL";
module.exports.URL_ANTECEDENTES_POLICIA = "https://antecedentes.policia.gov.co:7005/WebJudicial/index.xhtml";
module.exports.URL_CONTRALORIA_PERSONA_NATURAL = "https://cfiscal.contraloria.gov.co/SiborWeb/Certificados/CertificadoPersonaNatural.aspx"
module.exports.URL_PROCURADURIA_PERSONA_NATURAL = "https://www.procuraduria.gov.co/CertWEB/Certificado.aspx?tpo=1"
module.exports.ANTICAPTCHA_KEY = "e2513609e3b73ad96181a9370e517bb6"
module.exports.DOWNLOADS_PATH_BASE = "B:\\ejemplo\\imgs"
module.exports.DOWNLOADS_PATH_FOLDER_CONTRALORIA = "contraloriaPersonaN"
module.exports.DOWNLOADS_PATH_FOLDER_PROCURADURIA = "imgs\\procuraduriaGeneral"
module.exports.FOLDER_PATH_SEPARATOR = "\\" 
module.exports.FILES_CHAR_SEPARATOR = "_"
module.exports.RESP_ANTIOQUIA = "medellin"
module.exports.RESP_COLOMBIA = "bogota"
module.exports.RESP_ATLANTICO = "barranquilla"
module.exports.RESP_CAUCA = "cali"
module.exports.PREG_ANTIOQUIA = "Antioquia"
module.exports.PREG_COLOMBIA = "Colombia"
module.exports.PREG_ATLANTICO = "Atlantico"
module.exports.PREG_CAUCA = "Cauca"
module.exports.RESP_RES1 = "7"
module.exports.RESP_SUM1 = "8"
module.exports.RESP_MULT1 = "6"
module.exports.RESP_MULT2 = "9"
module.exports.PREG_RES1 = "9 - 2"
module.exports.PREG_SUM1 = "5 + 3"
module.exports.PREG_MULT1 = "2 X 3"
module.exports.PREG_MULT2 = "3 X 3"